version: "3.7"

services:
    database:
        build: ./MSSQL
        ports:
          - "1433:1433"

    myapp:
        build: ./PHP
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - task
        links:
          - "database"

networks:
    task:
        driver: bridge
